### ISSUE TITLE
How to access major, minor and patch within a kts script?

### ISSUE THREAD

**Issue by juxeii** [vivin/gradle-semantic-build-versioning#101]
Hi,

does anyone know how to access the property `major` in a kotlin DSL buildscript?
`val major = project.version.major as Integer` gives the error 

> Unresolved reference: major

I also tried to find the version properties in the `extra` properties map, but it is empty.

**Comment by vivin** [comment]
@juxeii Unfortunately not. I haven't tried to use this with kotlin. What happens when you output `project.version`? There may be some interop issues between kotlin and groovy?

**Comment by juxeii** [comment]
@vivin Here is the solution for this: [klick](https://github.com/gradle/kotlin-dsl/tree/master/samples/groovy-interop) It is not nice though :)
Issue can be closed.
