### ISSUE TITLE
Unable to specify suffix to be included in version

### ISSUE THREAD

**Issue by matthewh86** [vivin/gradle-semantic-build-versioning#105]
### Issue

Hello! I'm attempting to implement the following versioning scheme:

- starting version 0.0.1
- use SNAPSHOT for changes after a tagged commit (e.g. 0.0.2-SNAPSHOT)
- use -RC for a commit merged back to master (e.g. 0.0.2-RC)
- further changes would then be 0.0.3-RC-SNAPSHOT, until merged to master, at which point it would be tagged as 0.0.3-RC
- a process external to code changes (in this case promote a release to a production environment) happens, which adds the root tag alongside that -RC tag (e.g. 0.0.3-RC would also be 0.0.3)

I don't think I can use the preRelease configuration, as there could be a version conflict if for some reason we tried to promote two release candidates with the same root version to production.

### Resolution attempt

I have tried the following tag pattern, but `./gradlew printVersion` yields the starting version again despite there being existing version tags (e.g. 0.0.1 and 0.0.1-RC).

```
tagPattern = ~/\d++\.\d++\.\d++-RC/
```

I also had to add a dummy preRelease section so that it ignores the -RC tags which look like a preRelease.

```
preRelease {
  startingVersion = 'PR.0'
  pattern = /PR/
  bump = {
    "PR.${((it - ~/^PR\./) as int) + 1}"
  }
}
```

**Comment by vivin** [comment]
I think the problem here is that `-RC` doesn't really fit with the semver standard. Anything after the semver is a pre-release identifier, and so would need to be treated as such. The `-SNAPSHOT` (or whatever you'd defined it as) suffix is only for local builds and isn't expected to be deployed.

**Comment by matthewh86** [comment]
We've worked around this by specifying that release versions have -RELEASE after the version, rather than doing it the other way round of having -RC for unreleased, and the vanilla version for released.

Closing issue.
