### ISSUE TITLE
Initial version should begin at 0.1.0

### ISSUE THREAD

**Issue by srs-bsns** [vivin/gradle-semantic-build-versioning#2]
As per your readme:

> startingVersion
> This sets the version to use when no previous tags could be found. By default it is set to 0.0.1. This must be a valid semantic-version string.

The initial version can not start with a `patch` as there is no code to patch. Initial version for pre-release should begin at `0.1.0`.
See the SemVer FAQ: http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase

**Comment by vivin** [comment]
@srs-bsns Sorry for the late response - I was on vacation. I was not aware of that little detail! Thanks for letting me know - I will fix this.

**Comment by vivin** [comment]
Addressed in 434bf29. Closing.
