### ISSUE TITLE
Could not autobump because the last commit message did not match the major 

### ISSUE THREAD

**Issue by nilavalagansugumaran** [vivin/gradle-semantic-build-versioning#21]
Hi,

I am new to grade and trying to make use of this plugin. When using    " project.version.with { startingVersion = '1.0.2' }" it works charm 👍  But struggling to get the autobump working. I tried with the commit messages - majorPattern=[1], minorPattern=[1], patchPattern=[0]
It keeps complaining "Could not autobump because the last commit message did not match the major (/^[major]$/), minor (/^[minor]$/), patch (/^[patch]$/), pre-release (/^[pre-release]$/), or release (/^[promote]$/) patterns specified in the auto bump configuration"

Below is my configuration,
   autobump {
            majorPattern =~ /^[bump-major]$/
            minorPattern =~ /^[bump-minor]$/
            patchPattern =~ /^[bump-patch]$/
        }
Please can you advice with an example commit message? Sorry to raise this as an issue as I can't find any forum to discuss this.

**Comment by nilavalagansugumaran** [comment]
I see the semantic build version class is getting executed and the commit messages doesn't match with the auto bump patterns. I am committing the code with the comments like "[major] version updated" etc, i don't see why this is not matching in the validations. 
Is there any way to see what has been returned from Git. Is there a way to enable more logging to see what lines are returned from Git? 

Something like, 
  Git git = new Git(repository)
            Iterator<RevCommit> logIterator = git.log().call().iterator()
            lines = logIterator.next().fullMessage.split(/\n/)
            **println(lines);**

**Comment by nilavalagansugumaran** [comment]
Hi, Commit with just [major] or [minor] ... solved the error. I also removed the custom configuration.

However the build versions are not updating. I was expecting the build version to increment from the value mentioned in the startingVersion. But it always generated the build with the number in the  startingVersion for any tasks that i run (bumpMajor ,bumpMinor...). I don't see any errors in the logs.

My configuration is as below, please can you advice? 
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.net.vivin:gradle-semantic-build-versioning:2.0.1"
    }
}

```
apply plugin: 'net.vivin.gradle-semantic-build-versioning'

project.version.with {

    startingVersion = '1.2.3'
}
```

**Comment by vivin** [comment]
Your first problem was that the regex was not valid; you have to escape `[` and `]`:

```
autobump {
    majorPattern =~ /^\[bump-major\]$/
    minorPattern =~ /^\[bump-minor\]$/
    patchPattern =~ /^\[bump-patch\]$/
}
```

Notice that the regex requires the **entire line** to match the pattern and so you must have a single line with just that pattern, as you discovered.

As far as build versions not updating, normally that happens when there is already a tag on `HEAD`. Do you have any such tags? Also, please post your full `build.gradle` - how are you setting the version on the published artifact?

**Comment by nilavalagansugumaran** [comment]
Hi Vivin,

Many thanks for reply. Please find the below build.gradle file and let me know if you need any more details,

```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.6.RELEASE"
        classpath "gradle.plugin.net.vivin:gradle-semantic-build-versioning:2.0.1"
    }
}


allprojects {
    group 'com.company.com'
    version '1.0-SNAPSHOT'
}

subprojects {
    apply plugin: 'java'
    apply plugin: "io.spring.dependency-management"
    apply plugin: 'maven-publish'

    apply plugin: 'net.vivin.gradle-semantic-build-versioning'

    project.version.with {

        startingVersion = '1.2.3'

        /*   preRelease {
       startingVersion = 'nila.0'

       bump { String version ->
           int num = Integer.parseInt(version.split(/\./)[1]) + 1
           return "nila.${num}"
       }
   }*/

    }

    publishing {
        repositories {
            maven {
                url "s3://repo.company.com/snapshot"
                credentials(AwsCredentials) {
                    accessKey AWS_S3_KEY
                    secretKey AWS_S3_SECRET
                }
            }
        }
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
    }

    repositories {
        maven {
            url "s3://repo.company.com/snapshot"
            credentials(AwsCredentials) {
                accessKey AWS_S3_KEY
                secretKey AWS_S3_SECRET
            }
        }
        mavenLocal()
        mavenCentral()
        //jcenter()
    }

    dependencyManagement {
        imports {
            mavenBom 'com.amazonaws:aws-java-sdk-bom:1.11.8'
        }
    }

    ext {
        slf4jVersion = '1.7.14'
        log4jVersion = '1.2.17'
        slf4jLog4jVersion = '1.7.21'
        junitVersion = '4.12'
        hamcrestVersion = '1.3'
        mockitoVersion = '1.8.4'
        swaggerAnnotationsVersion = '1.5.8'
        lambdaLog4jVersion = '1.0.0'
        lambdaJavaCoreVersion = '1.1.0'
        lambdaJavaEventVersion = '1.3.0'
        jacksonVersion = '2.7.4'
        springfoxVersion = '2.4.0'
        javaxWsRsApiVersion = '2.0.1'
        genFolder = '../src/main/generated'
        jacksonAnnotationsVersion = '2.7.4'
        apacheCommonsLangVersion = '3.4'
        apacheHTTPClientVersion = '4.5.2'
        iojjwtVersion = '0.6.0'
        orgJsonVersion = '20160212'
        simpleFrameworkVersion = '5.1.6'
    }

    dependencies {
        compile group: 'org.slf4j', name: 'slf4j-api', version:"${slf4jVersion}"
        compile "log4j:log4j:${log4jVersion}"
        compile "org.slf4j:slf4j-log4j12:${slf4jLog4jVersion}"
        testCompile "junit:junit:${junitVersion}"
        testCompile group: 'org.hamcrest', name: 'hamcrest-all', version:"${hamcrestVersion}"
        testCompile group: 'org.mockito', name: 'mockito-core', version:"${mockitoVersion}"
        compile group: 'com.google.inject', name: 'guice', version: '4.1.0'
        compile group: 'javax.jcr', name: 'jcr', version: '2.0'
        // https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-core
        compile group: 'com.amazonaws', name: 'aws-java-sdk-core', version: '1.11.29'

    }
}
```

**Comment by vivin** [comment]
Some questions:
1. Is this a multiproject?
2. Have you already created a tag and is HEAD at that tag?
3. What is your previous commit message?
4. What is the gradle command you are using when you build?

**Comment by nilavalagansugumaran** [comment]
Hi Vivin,
Yes it is a multiproject. I now figured it what went wrong. When checking-out the project, I dint have the Git Tag with the version. As soon as i added the tag (plugin is based on tag, my mistake, somehow i have missed it), all the commands stared working charm 👍 

The process I now have is (may be useful to others),
1) get the git tags and check if any tags available.
2) if no, get the startingVersion from the build.gradle file and add a tag using the start version
3) run the  build with bump options
4) add a new tag in git with the updated version
5) update the start version in gradle file 

Many thanks for your help!
