### ISSUE TITLE
Version number after checking out a tag and making changes should be scoped to the major-minor version from that tag

### ISSUE THREAD

**Issue by vivin** [vivin/gradle-semantic-build-versioning#22]
When someone checks out a tag and makes changes, the plugin calculates the new version using the latest version _overall_. Instead, the latest version should be scoped to the major and minor version from that tag. For example, suppose we have tags 2.0.0, 1.2.2, 1.2.1, 1.2.0 and we check out 1.2.0 and make changes. If we bump the patch-version for example, the new version should be 1.2.3 instead of 2.0.1.

**Comment by Vampire** [comment]
PR #43 should take care of this issue

**Comment by vivin** [comment]
:+1:
