### ISSUE TITLE
version to not consistent 

### ISSUE THREAD

**Issue by brolinuk** [vivin/gradle-semantic-build-versioning#30]
Hi there

I am quite new to gradle and trying to use the semantic build versioning in our project, but having problem when try to  publish a zip file to nexus server in the child project

In the parent project, I publish the parent jar file to Nexus 

```
..
        classpath "gradle.plugin.net.vivin:gradle-semantic-build-versioning:2.0.2"
...

apply plugin: 'net.vivin.gradle-semantic-build-versioning'
    project.version.with {
        startingVersion = '1.6.0'
}


uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: NEXUS_RELEASE_URL) {
                authentication(userName: NEXUS_USER, password: NEXUS_PASSWORD)
            }
            snapshotRepository(url: NEXUS_SNAPSHOT_URL) {
                authentication(userName: NEXUS_USER, password: NEXUS_PASSWORD)
            }
        }
    }
}
```

In one of its child project, I tried to use maven publish plug to publish its zip distribution to nexus. 

```
publishing {
    repositories {
        maven {
            url NEXUS_SNAPSHOT_URL
            credentials {
                username NEXUS_USER
                password NEXUS_PASSWORD
            }
        }
    }
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifactId 'content-aws-lambda'
            artifact buildZip
        }
    }
}
```

My current git tag is 1.5.0. 

When try to run the version build 
_gradle clean bumpMinor build publish printVersion_

It complains file not exist
_
Execution failed for task ':endpoints:amazon-lambda:publishMavenJavaPublicationToMavenRepository'.

Invalid publication 'mavenJava': artifact file does not exist: '/Users/xxx/xx/amazon-lambda/build/libs/amazon-lambda-1.5.1-SNAPSHOT.jar'_

I can see the files was built at libs/amazon-lambda-1.6.0-SNAPSHOT.jar, (I can also see amazon-lambda-1.6.0-SNAPSHOT.zip file was built in the distribution folder, which is the one I actually want to publish) but not sure why the publish still trying to find 1.5.1 version. It looks like it can only understand as a patch bump rather than minor bump. 

I saw someone mentioned about the compatibility issue with Maven publish plugin, but not sure whether it is the case for me. Could you please advise how to solve this issue. Many thanks.

**Comment by vivin** [comment]
Yes, unfortunately this is a problem with the `maven-publish` plugin in some cases. Since marker tasks control version numbering, this is not done until after the task-graph is ready. It looks in some situations, the `maven-publish` plugin will use the initial version that it gets to decide the name of the artifact file. I haven't identified the particular situation because I've used this plugin with `maven-publish` without issue (the plugin uses itself for versioning and uses `maven-publish` as well).

One thing you can do is reset the version for the publication in a `whenReady` block. Something like:

```
project.gradle.taskGraph.whenReady {
    project.tasks.jar.version = project.version // You may need this to set the version on the jar properly
    project.publishing.publications.mavenJava.version = project.version
    project.publishing.publications.mavenJava.artifacts = [
        project.tasks.jar // reset the artifacts
    ]
}
```

One thing you may also have to do is reset the version in the `buildZip` task inside `whenReady`, if the task also uses the version number.

**Comment by brolinuk** [comment]
Hi,  thanks for the reply. Your code does help to solve the version issue for the jar dependency (publish the jar to nexus with correct version). However, I am not sure why the publish ignore the zip file created in the distribution folder with the correct version I would expect. 

Without implementing the version plugin, the zip file published together with jar correctly. 

```
task buildZip(type: Zip) {
    from compileJava
    from processResources

    into('lib') {
        from configurations.runtime
    }
}
```

Do I need to update the zip version like what have been done in the whenReady? It seems that project.tasks.zip is not allowed. Please advise. Many thanks

**Comment by vivin** [comment]
@brolinuk Yes, you would have to do the same thing with the `buildZip` task. Instead of `project.tasks.zip` however, you would have to use `project.tasks.buildZip`.

**Comment by brolinuk** [comment]
Thanks. I have figured that out. Really appreciate your help

```
    project.publishing.publications.mavenJava.artifacts = [
            project.tasks.jar, buildZip]
```

**Comment by vivin** [comment]
Glad to help!
