### ISSUE TITLE
Need annotated tag for Gerrit

### ISSUE THREAD

**Issue by rednuht** [vivin/gradle-semantic-build-versioning#34]
Hi,

We want to use this plugin for our project* but we are using(forced by the company :P) Gerrit, and it allows only annotated tags to be pushed to it.

I'm thinking that there should be a way of determining automatically whether or not the tag should be annotated based on the configuration. If the user has defined the message to be used for annotated tags then the tag should be created as annotated=true, and false otherwise. However, I don't know what would be the best way to do it :)

Would it be possible to add this?

*(the project is quite large and will be used by many people(>500), it would be great if we could use something that already exists instead of having to create something ourselves)

**Comment by vivin** [comment]
Sorry for the late response. I am sure we could do something like this.

**Comment by rednuht** [comment]
Any updates? We are currently using an older version of your plugin (2.0.0) and we would really be happy if this could be done.

**Comment by vivin** [comment]
@rednuht Version 3.0.0 should be out soon. I'm juggling work and my PhD so things hvae been pretty busy. 

Version 3.0.0 will have better config as well since it will be a settings plugin. There are few PRs I have to merge.

**Comment by vivin** [comment]
@rednuht For the annotated tag's message, is the something like `v1.0.0` fine?

**Comment by rednuht** [comment]
I understand, everything is working fine at the moment so take your time :)

Yes that would work.

**Comment by vivin** [comment]
@rednuht Version 3.0.0 is out and it has significant improvements. It is now a settings plugin as well, so you don't run into the late-configuration issues that the prior versions had (because tags controlled version bumping, the version wasn't ready during config time).
