### ISSUE TITLE
Can't find latest version 3.0.0

### ISSUE THREAD

**Issue by smccauliff** [vivin/gradle-semantic-build-versioning#41]
I've followed the instructions in the latest README.md file and I still get this error.   Is the plugin artifact not yet published to the gradle repository?

* What went wrong:
Could not resolve all dependencies for configuration 'classpath'.
> Could not find gradle.plugin.net.vivin:gradle-semantic-build-versioning:3.0.0.
  Searched in the following locations:
      https://plugins.gradle.org/m2/gradle/plugin/net/vivin/gradle-semantic-build-versioning/3.0.0/gradle-semantic-build-versioning-3.0.0.pom
      https://plugins.gradle.org/m2/gradle/plugin/net/vivin/gradle-semantic-build-versioning/3.0.0/gradle-semantic-build-versioning-3.0.0.jar
  Required by:
      unspecified:unspecified:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by vivin** [comment]
@smccauliff 

Sorry; it hasn't been released yet - it is still WIP. I'm still working on getting the tag annotation feature in - should hopefully be done by the weekend.

I will add a disclaimer in the README or put up a badge for the latest version.

**Comment by vivin** [comment]
@smccauliff Version 3.0.0 is out now.
