### ISSUE TITLE
Getting "org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to org.gradle.api.initialization.Settings".

### ISSUE THREAD

**Issue by Pralhadb** [vivin/gradle-semantic-build-versioning#75]
I have used below plugin in my build.gradle:
`` apply plugin: "net.vivin.gradle-semantic-build-versioning"

dependencies {
				classpath "gradle.plugin.net.vivin:gradle-semantic-build-versioning:3.0.4"
		}

 but, I am getting "org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to org.gradle.api.initialization.Setting" exception with this .

**Comment by vivin** [comment]
@Pralhadb This is a settings plugin, so it must be applied inside `settings.gradle`. Take a look at the README; it explains how to set it up.
