### ISSUE TITLE
Feature branch dev workflow

### ISSUE THREAD

**Issue by tobad357** [vivin/gradle-semantic-build-versioning#83]
Hi
We have a workflow where we use feature branches
This means that each dev may be working on the same sub project but in different branches.
Is there anyway to get the version suffixed with the branch name (see https://github.com/nebula-plugins/nebula-release-plugin and their shortenedBranchPattern property)

**Comment by vivin** [comment]
Yes, you can definitely do that. See [here](https://github.com/vivin/gradle-semantic-build-versioning/issues/74) for an example.

**Comment by vivin** [comment]
@tobad357 Did that address your issue?
