### ISSUE TITLE
specify bump up minor by default

### ISSUE THREAD

**Issue by DemianTinkiel** [vivin/gradle-semantic-build-versioning#89]
I would like to do something like
```
autobump {
    majorPattern = ~/(?m)^\[major-release\]$/
    patchPattern = ~/(?m)^hotfix$/
}
```
<assume starting from v1.0.0>

> 
> 1: git commit -m "normal stuff" -> v1.1.0
> 2: git commit -m "hotfix" -> v1.1.1
> 3: git commit -m "[major-release]" -> v2.1.1

but when I do case 1 I get a bump in patch component, not minor

**Comment by vivin** [comment]
@DemianTinkiel You'd have to set a pattern that matches anything except `hotfix` or `[major-release]` for `minorPattern` I would think.

**Comment by DemianTinkiel** [comment]
Hi @vivin 
Yeah that was my first thought. Perhaps my regex foo is not as strong as I thought
```
    majorPattern = ~/(?m)^\[major-release\]$/
    patchPattern = ~/(?m)^hotfix$/
    minorPattern = ~/^(?!(.*(hotfix|\[major-release\]).*))$/
```
1: git commit -m "normal stuff" gives me v1.0.1 and I expected v1.1.0

**Comment by vivin** [comment]
Perhaps `~/^(?!.*(hotfix|\[major-release\]))/`?

**Comment by Nols1000** [comment]
For me this regex works great you could change it for your use case:

````groovy
minorPattern = ~/(?m)^(?!(.*(\[bump-major\]|\[bump-patch\]|\[make-new-pre-release\]|\[promote-to-release\]).*)$).*$/
````

**Comment by vivin** [comment]
@DemianTinkiel Did this fix your issue?

**Comment by DemianTinkiel** [comment]
@vivin sorry for the really late reply. Yes issue fixed
